### ISSUE TITLE
Improve UI and working of Bottom Navigation Bar

### ISSUE THREAD

**Issue by tushant-akar** [iiitv/PollPulse-Kotlin#1]
**Objectives:**

![Screenshot 2024-09-30 204629](https://github.com/user-attachments/assets/3e3cca8c-e07e-4c37-ab1f-d3921849e9f2)

- Improve the UI of the Bottom Navigation Bar as given in the [Figma Design](https://www.figma.com/file/KAAj6qMlkKJ0HG39omnXkP/Voting-app?type=design&node-id=0%3A1&mode=dev)
- Remove the loadFragment() function and use better approach for navigation using Bottom Navigation Bar.

**Comment by Harini-01** [comment]
Hey @tushant-akar, I would like to work on this issue. I am participating in the hacktoberfest-2024. This would be my first open source contribution.

**Comment by Tisha187** [comment]
@Harini-01  Issue Assigned to you.

**Comment by Harini-01** [comment]
Hey @Tisha187 , I have made changes to the code. This is how the bottom navigation bar appears now.
Before
![WhatsApp Image 2024-10-02 at 18 19 34_20e6315e](https://github.com/user-attachments/assets/5e99a6c7-563b-44fa-a2c2-d489341c4e75)
After
![WhatsApp Image 2024-10-02 at 18 19 34_69d3a67d](https://github.com/user-attachments/assets/a5e13a4d-0baf-4539-a30c-bcdbc921dedd)
![WhatsApp Image 2024-10-02 at 18 19 35_484f0cc2](https://github.com/user-attachments/assets/b13eff63-7a76-4a40-ac34-975e85f42583)
Do you want me to remove the pinkish shadow around the selected item?

**Comment by tushant-akar** [comment]
@Harini-01 Also remove the pinkish shadow and the selected item should not pop up on clicking.

Do the required changes as mentioned.

**Comment by Harini-01** [comment]
@Tisha187 I have submitted the pr. Kindly review it.

**Comment by Harini-01** [comment]
@tushant-akar Could you please confirm if this project comes under hacktoberfest - 2024?

**Comment by tushant-akar** [comment]
@Harini-01 Yes this project comes under Hacktoberfest.

**Comment by Harini-01** [comment]
![image](https://github.com/user-attachments/assets/8f9ed94e-30d7-475d-86ef-3587ac7a14a0)
![image](https://github.com/user-attachments/assets/f17f4baa-5198-4a3e-82f0-131627dc328c)

@tushant-akar But my dashboard says the project repo is not under hacktoberfest. Could you please check?

**Comment by tushant-akar** [comment]
@Harini-01 Added hacktoberfest-accepted label to your PR.

**Comment by Harini-01** [comment]
The pr got accepted. Thank you.
